### PR TITLE
Initialize help book bundle

### PR DESCRIPTION
**Pull request by tzvipm**
## Summary
Initialize a help book bundle. This will make it easier for users to discover features such as keyboard shortcuts.

Based on instructions here: https://developer.apple.com/library/archive/documentation/Carbon/Conceptual/ProvidingUserAssitAppleHelp/authoring_help/authoring_help_book.html#//apple_ref/doc/uid/TP30000903-CH206-CIHEAADH

Before:
before-help

After:
after-help

## Related Issues
First step in https://github.com/xi-editor/xi-mac/issues/252

Prior work: https://github.com/xi-editor/xi-mac/pull/262

## Checklist
Example:

- [x] Initialize `XiEditor.help` bundle
- [x] Create a title page
- [x] Add a page with keyboard shortcuts

## Review Checklist

- [ ] I have responded to reviews and made changes where appropriate.
- [ ] I have tested the code
- [ ] I have updated comments / documentation related to the changes I made.
- [ ] I have rebased my PR branch onto xi-mac/master.

### CODE REVIEW

**Comment by jansol** [comment]
Does this actually change anything on top of #262 or is it still WIP?

**Comment by tzvipm** [comment]
@jansol, sorry, this is still WIP, although I wanted to make sure that everything looked good in TravisCI, since it seems to have been failing on #262

**Comment by tzvipm** [comment]
@jansol, I don't like the way the editing flow works in XCode for the help book. The help bundle shows up, for me, as a bundle file, and I have to edit the html files via `cd`ing into the folder in my terminal and using my text editor (or even `xed` for that matter).

What do you think of the idea of adding a build step (or some sort of script) to generate the help bundle from a series of markdown files? Or even simpler would be to expose the html files, but to package them as a `.help` bundle in a build step.

**Comment by tzvipm** [comment]
Preview of pages so far:
screen shot 2018-12-04 at 12 06 00 pm
screen shot 2018-12-04 at 12 06 07 pm
screen shot 2018-12-04 at 12 06 14 pm

**Comment by jansol** [comment]
I'm open to any alternatives that work and don't make a mess. If it's easy to mirror to xi-editor.io, all the better.

**Comment by tzvipm** [comment]
@jansol I think this is in a good state to be merged at this point. Further iterations can improve on the documentation, as well as the build flow, but this definitely gets the ball rolling. Thoughts?

**Comment by jansol** [comment]
Filling out the hotkey tables should be easy fairly trivial so I personally don't mind leaving that for a separate PR. However I'd very much like to fix this up to look a bit more professional before merging. Namely:
* [ ] Use the similar font sizes as in the [Mail User Guide](https://support.apple.com/guide/mail/write-and-send-emails-mlhlp1121/12.0/mac/10.14.1).
* [ ] Use the same fonts as [xi-editor.io](https://xi-editor.io/)
* [ ] Make the app icon show up on every page to the left of the title, like in Mail Help (on the same line as the title, not separately like it is now on the index page)
* [ ] Ensure that all tables in the hotkey page have the same width
* [ ] Add a `<hr />` between sections (so far only between tables on the hotkey page)
* [ ] Change the index page title to "Xi-Editor User Guide"
* [ ] Give the index page a header div styled like the header of [xi-editor.io](https://xi-editor.io/) (optional)

**Comment by jansol** [comment]
By the way, what happened to the generating help pages from markdown part? That would further have the benefit of being easy to share with the official xi-editor website.

**Comment by tzvipm** [comment]
screen shot 2018-12-14 at 8 56 03 pm
screen shot 2018-12-14 at 8 56 10 pm
screen shot 2018-12-14 at 8 56 19 pm

**Comment by jansol** [comment]
Excellent. One pet peeve of mine: if you could use the imperative form for future commit messages (and pulll request titles) that would be awesome as it tends to look much more natural in commit logs.

[This](https://chris.beams.io/posts/git-commit/) is an excellent guide to writing commit messages. No need to stick 100% strictly to it but using it as a rough guideline makes the life of everyone who has to sift through commit logs a lot easier.

**Pull request merged**
