### PR TITLE
Fix selection rendering and prevent crashes

### PR DESCRIPTION
**Pull request by scholtzan**
This fixes https://github.com/xi-editor/xi-mac/issues/434 and https://github.com/xi-editor/xi-mac/issues/433. I am not entirely sure why...

### CODE REVIEW

**Comment by mmatoszko** [comment]
Shouldn't the `startColumn` and `endColumn` of the `Annotation` be already translated into UTF-16 while we create the `Annotation` struct? I think this could simplify the math here 😄
Or maybe there is a specific reason to use UTF-8 all over the Mac app?

**Comment by scholtzan** [comment]
I looked a bit more into this. I examined the values on the following line which produced the issues:

“Let’s have it quick, Jack,” Bob called, as he stuck his head in at the

The `line.text.count` for the line is 72. If I move the cursor to the end of the line then the utf16 value of the position is 71, the utf8 one is 77. So `line.text.count` seems to already be in utf16. `0` in utf8 is the same in utf16. 

Similar results for other lines. So I believe that confirms what @cmyr mentioned.

**Comment by mmatoszko** [comment]
Fun fact: this might resurface around [Swift 5](https://forums.swift.org/t/string-s-abi-and-utf-8/17676)

**Comment by cmyr** [comment]
Good note @mmatoszko, we'll have to remove various utf-16 conversion code when we do that migration.

And to satisfy my own curiosity, I can confirm that `“ (u+201c)` and `’ (u+2019)` are each 3 code units in utf-8 but only 1 in utf-16.

**Pull request merged**
