### PR TITLE
480 Drag events cause file to be opened

### LINKED ISSUE #480: Drag events cause file to be opened
# Xi-Mac Issue Template
- [x] I have searched existing issues and could not find my issue.
- [x] I have studied the documentation.

## Details

OS X 10.14.6

## Expected vs Actual

Actual: I noticed that xi opens files which are dragged across it's window frame. This occurs even if the file is not released on the xi frame. This occurred to me several times when I was dragging files from the Finder into my email client. They just happened to cross the xi window frame.

Expected: xi should not open files unless they are released/dropped on it's frame.

PS thanks for this app! I love how fast and responsive it is.

### PR DESCRIPTION
**Pull request by mohanio**
## Summary
#480  Drag events cause file to be opened

Issue:
* Files dragged over XiEditor window and dropped elsewhere is opened by XiEditor.
* This is becasue file open is triggered from draggingEnded(_:) which is invoked immeterial of drop location

Fix:
* Use draggingEntered(_:) to return the dragging operation that XiEditor will perform when dropped
* Trigger file open from performDragOperation(_:) delegate callback

## Related Issues
closes #480

## Checklist
Example:

- [ ] Example check-list item
- [x] Create a pull request template
- [ ] make xi perfect

## Review Checklist

- [ ] I have responded to reviews and made changes where appropriate.
- [ ] I have tested the code
- [ ] I have updated comments / documentation related to the changes I made.
- [ ] I have rebased my PR branch onto xi-mac/master.

### CODE REVIEW

**Comment by mohanio** [comment]
> Thanks for this, looks good to me, though I'd like the issue number to be removed from the commit message and instead have the link to the issue in the commit message body.

Thanks for the opportunity, would like to involve and contribute more. Made necessary changes to commit message.

**Comment by nangtrongvuon** [comment]
Oh, no, not like that. Your commit message has to be a short description of what you did.
You can read more on that [here](https://chris.beams.io/posts/git-commit/).

**Comment by mohanio** [comment]
> Oh, no, not like that. The body is fine, but your commit message has to be a short description of what you did.
> You can read more on that [here](https://chris.beams.io/posts/git-commit/).

Please merge the PR if it looks good.

**Comment by nangtrongvuon** [comment]
All good, thanks for this!

**Pull request merged**
