### PR TITLE
Fix scroll jitter during rewrap

### PR DESCRIPTION
**Pull request by cmyr**
This is client support for https://github.com/xi-editor/xi-editor/pull/1066. It also includes the commit from #392; if that gets merged first I'll rebase.

## Review Checklist

- [ ] I have responded to reviews and made changes where appropriate.
- [ ] I have tested the code
- [ ] I have updated comments / documentation related to the changes I made.
- [ ] I have rebased my PR branch onto xi-mac/master.

### CODE REVIEW

**Comment by jansol** [comment]
1) Open a long file
2) Scroll almost all the way down
3) Observe empty view for a few seconds
4) Click on it
5) A wild selection appears! It's super effective! Scroll state spazzed out!

**Comment by cmyr** [comment]
is this with sqlite.c?

**Comment by jansol** [comment]
With my IRC logs, but I guess sqlite3.c would do the same given a sufficiently narrow window. (albeit with slightly shorter delays before it's done rewrapping)

**Comment by cmyr** [comment]
hmm i'm not totally sure what your'e describing, but I wonder if it's related to not having https://github.com/xi-editor/xi-editor/pull/1065?

there is a bunch of stuff in flight, should probably rationalize. that, I don't even know what combination of commits I'm running atm 😕

**Comment by cmyr** [comment]
hmm okay I think I see your issue.

**Comment by jansol** [comment]
I did pull xi-editor/xi-editor#1066 and rebase it on top of xi-editor/xi-editor#1065 so I don't think that is the problem.

**Comment by cmyr** [comment]
So @jansol's bug has revealed a fundamental problem here, which is that the frontend's line state and core's line state can get out of sync, and this can't be reasonably addressed without either limiting asynchrony or sending revision IDs back and forth with movement commands; in any case this needs more thought.

**Pull request closed without merging**
